name: Build and Push AnyCDC Docker Image

# 触发条件：打 Tag 时触发
on:
  push:
    tags:
      - '*'

# 权限配置（用于获取 Git Tag）
permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Go 环境（构建服务端）
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # 根据你的项目 Go 版本调整
          cache: true # 启用 Go 模块缓存

      # 3. 构建 Go 服务端二进制程序（Linux 平台）
      - name: Build Go server binary
        run: |
          cd cmd/server
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o anycdc-server -ldflags="-s -w" .
          ls -lh anycdc-server

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 根据你的 Vue 项目 Node 版本调整
          cache: 'npm'
          cache-dependency-path: cmd/dashboard/package-lock.json

      - name: Build Vue dashboard
        run: |
          cd cmd/dashboard
          yarn
          yarn build
          ls -lh dist/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 7. 登录 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract Git Tag
        id: extract_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: miskolee/anycdc:${{ steps.extract_tag.outputs.TAG }}